title: WodToolKit
description: 轻量级.NET工具库，提供各类常用功能的封装
baseurl: "/WodToolkit"
url: "https://thiswod.github.io"

# 使用自定义布局
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "index.md"
    values:
      layout: home

# 排除文件
exclude:
  - Gemfile
  - Gemfile.lock
  - README_EN.md
